[package]
name = "crawler"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.5.0"
surf = "2.0.0-alpha.0"
html5ever = "0.25.1"
url = "2.1.0"